### ISSUE TITLE
Run on usb device

### ISSUE THREAD

**Issue by fabiomaia** [matsp/docker-flutter#2]
Hey this is very cool, thanks for sharing! I want to introduce a completely dockerized Flutter development environment in my team to avoid reproducibility issues, but the Flutter setup is very convoluted and I'm very new to Flutter and Android in general too so it's taking a while to figure out 100%.

- How do you run this on a USB-connected device? I had some luck with `--privileged` previously but not with your setup for some reason
- Why not run from the official `cirrusci/flutter` images? They are built automatically by the Flutter team's CI/CD, so the version maintenance would be offloaded to them. This could be just a "frontend" script that developers add to their `$PATH` after which they can transparently run `flutter` normally
- Any thoughts on silencing the inevitable warning when you switch between Flutter SDKs?

```
Warning! This package referenced a Flutter repository via the .packages file that is no longer available. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /home/fabio/bin/flutter
  previous reference  : /opt/flutter
This can happen if you deleted or moved your copy of the Flutter repository, or if it was on a volume that is no longer mounted or has been mounted at a different location. Please check your system path to verify
that you are running the expected version (run 'flutter --version' to see which flutter is on your path).
```

**Comment by matsp** [comment]
Hi @fabiomaia !

1. You can map USB devices with `--device /dev/usb`, like I map the KVM device in the examples. But you need to know the exact device everytime. Maybe we can improve the setup for `adb`.

2. My knowledge about the `cirrusci/flutter` image is that it is not officially build by the flutter team. Or did I understand you wrongly? I build the image on my own because I want a complete setup that is working out the box. I tested several other flutter images and had always problems with my setup.

3. I am only using the flutter image and don't have a local flutter installed. But I think it is not fixable because the cli write some information in the file you mentioned.

**Comment by matsp** [comment]
... actually I am also working on running this image with the vscode remote extensions (running in the container).

**Comment by oliverpool** [comment]
> running this image with the vscode remote extensions

I had success following this post: https://blog.codemagic.io/how-to-dockerize-flutter-apps/

**Comment by matsp** [comment]
@oliverpool Haha yes. I am actually preparing the commit for the README.

**Comment by fabiomaia** [comment]
As I understand it, cirrusci/flutter is built by the Flutter team https://github.com/flutter/flutter/blob/master/.cirrus.yml

VSCode integration seems very convenient but locks developers into VSCode.

**Comment by matsp** [comment]
CirrusCI is a product not owned but used by Google. The flutter team build their product at CirrusCI. But the flutter team is not building the image you posted.
